### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wilsoncai1992** [wilsoncai1992/adaptest#8]
- [x] change core class to S4 based on `SummarizedExperiment`
- [ ] re-write plotting functions to use `ggplot2` (@nhejazi)
- [x] add auto-builds for Windows via [Appveyor](https://www.appveyor.com) (@nhejazi)
- [x] switch testing / code coverage to [codecov.io](https://codecov.io) (@nhejazi)
- [x] correct notation to be consistent with Alan + Mark's 2016 IJB paper (@wilsoncai1992)
- [x] prepare package/documentation for submission to __BioC__
- [x] write suite of unit tests

**Comment by nhejazi** [comment]
@wilsoncai1992 some changes for the manuscript on Overleaf

**Comment by wilsoncai1992** [comment]
Thank you so much nima! I will look into it today or tomorrow

**Comment by nhejazi** [comment]
@wilsoncai1992, I can't edit the URL associated with the repo description, so if you could add this URL to that https://wilsoncai1992.github.io/data.adapt.multi.test/
